### ISSUE TITLE
docstring for TimeSeries.fixed_window_rollup needs updating

### ISSUE THREAD

**Issue by jdugan1024** [esnet/pypond#10]
The example has this: (https://github.com/esnet/pypond/blob/master/pypond/series.py#L1163)

```
daily_avg = timeseries.fixed_window_rollup('1d', {'value': Functions.avg()})
```

Which doesn't work.  It's now a nested dict that has output as the first key and input as the second key.

This paragraph doesn't describe the current behavior:  https://github.com/esnet/pypond/blob/master/pypond/series.py#L1151

There may be other things that need updating in the docstring, but that's what I noticed off the bat.

**Comment by montegoode** [comment]
Addressed by: https://github.com/esnet/pypond/pull/11
