### ISSUE TITLE
Easier UNIX timestamp

### ISSUE THREAD

**Issue by pjm17971** [esnet/pypond#13]
From the GCP project, we wanted to say `timeseries.begin()` and then get the UNIX timestamp (ms since the epoch). It seemed pretty ugly to try and do this. In JS it's `timeseries.begin().getTime()`. So it would be nice if the library helped with that, because when interacting with other systems this is kind of helpful.

So maybe `timeseries.beginTimestamp()` and `timeseries.endTimestamp()`. These would probably call though to the TimeRange, which would have the actual implementation of that.

Seem reasonable. Kind of simple thing, but the API forced @sartaj10 into grabbing the points themselves and picking off the first element of the first one. So that's probably not what we want people to do.

**Comment by montegoode** [comment]
`pypond.util.ms_from_dt()` already handles this. Adding this will be trivial.

**Comment by pjm17971** [comment]
Yeah, later in the weekend we found that function, but I still think this would be useful (as it's less obvious to use the util function). Not an urgent issue, I just wanted to note it.

**Comment by montegoode** [comment]
Addressed by: https://github.com/esnet/pypond/commit/bab49b908d0b84009c471b75011d60ad3174acb0
