### ISSUE TITLE
Timeseries out of order events

### ISSUE THREAD

**Issue by pjm17971** [esnet/pypond#14]
I'm assuming this is an issue for PyPond too, but when we use TimeSeries.merge, the events are broken down to a map with timestamp as the key. For one, the order of this list isn't really guaranteed, although in JS it kind of is. The real issue is that if the begin times of the TimeSeries are out of order (and there's no reason why they wouldn't be), then the keys will be out of order and therefore the result will be too. That result is then used for building a new TimeSeries result and it throws an non-chronological events exception.

For the JS code, I check isChronological on the result in the TimeSeries.merge, and if it isn't I sort the events. We could probably save doing this if we (maybe in addition), sorted the incoming seriesList by begin time. I also relaxed the TimeSeries constructor to do the isChronological check and sort, along with issue a warning. This seems a little kinder of developers, but still lets them know they might be getting themselves into a performance issue.

**Comment by montegoode** [comment]
I'm going to implement the "maybe in addition" logic as well. It seems like that sort is potentially cheaper, and then leave the other one in place to handle situations that we are not currently envisioning?

**Comment by montegoode** [comment]
Fixed with: https://github.com/esnet/pypond/commit/03443e0e2d55e70301d913d8f66872dfdf838007

Currently only using the "order the incoming TimeSeries by begin time" method because I can ensure the event map ordering, so the `.is_chronological()` test should be superfluous. Will revisit if necessary.
