### ISSUE TITLE
Collect Dataflow use cases

### ISSUE THREAD

**Issue by pjm17971** [esnet/pypond#6]
This issue is for discussion of how PyPond might help us with Dataflow processing. Here I'll clarify what PyPond can already do and what it will be able to do in the near future. In addition, the state of Dataflow and Python is a little tricky, so that needs to clarified here as well.

**What Pond can do?**

At its heart, Pond is a set of immutable data structures and a transmitting format to send them across the wire. The structures in Pond are:
- `TimeRange` - a begin and end time and methods for manipulating and comparing them
- Events - an event is a time or time range associated with a dict of data. The three types are `Event`, which is a keyed off a time stamp, TimeRangeEvent which uses a `TimeRange` and `IndexedEvent` which uses a string notation to specify a region of time ("1d-1234" for a fixed time region, or "2014-06" for a month).
- `Collection` - a structure that holds a bag of Events. The Events don't have to be ordered in any particular way. The `Collection` has a bunch of functionality on it to process and aggregate its contents. for instance, you could get the `avg()` of all the events "in" value with `collection.avg("in")`. The collection is the backing structure for a `TimeSeries`, as well as being used in processing (such as aggregating incoming events into a `Collection` and then emitting out a result).
- `TimeSeries` - this was the main point of the library. This is a `Collection` that contains homogeneous and chronological events. It has a bunch of methods that specifically deal with this type of data. The string output of a `TimeSeries` is what we use as a Tile.
- Pipelines - a pipeline is similar in some ways to Dataflow (and in other ways not so much). Pipelines stream events through processors. They can make collections (such as to build a tile) and then be used to build. So you can stream events into a Pipeline and have it group them, then build a collection based on a window, then emit that window as a tile, or aggregate that window into a new event that can then continue down the Pipeline. You can also run a pipeline directly off a `TimeSeries` and it will basically take the events in the `TimeSeries` and stream them through the pipeline.

**New code needed for the GCP project**

We are currently adding better ability to process data with missing values. This is primarily to support backend processing that needs to deal with bad real world data. Planned updates include:
- aggregation functions are filter aware, so you can tell them to ignore None and NaN values, for instance
- `fill()` operation to fill in holes in an existing TimeSeries (to some limit), in various ways
- `align()` operation to place irregular data onto regular time boundaries (like the 30s base rate)
- `rate()` operation to transform 30s aligned counters (for example) to base rate events.
  Plus some other stuff like column renaming.

**Dataflow constraints**

Finally its worth noting that we can only potentially use PyPond on the batch part of our processing since the python API to Dataflow does not support streaming (YET). We should keep in mind (and to some extent plan for) being able to do streaming in Python, because a) we can use PyPond and its test suite and b) because generally Python is easier for us to maintain and develop in.

For the batch path, the main tasks we try to accomplish are:
- Periodically (every night, for example) take a set of rows from the BigQuery table containing the raw SNMP counters and process that as Base Rate 30s rows into another table.
- Periodically take the Base Rate 30s rows and generate rollups: 5m avg, 1hr avg and 1day avg. These are written into another table.
- Periodically take these rollups and collect them together into tiles. Each tile is a string of json, which is the wire format for a Pond TimeSeries. We have 1 day, 7 days and 90 day tiles right now. For example a 1 day tile is a timeseries of 2880 30s base rate samples, while a 7 day take is a timeseries of 5m avg. Each tile has a particular key associated with it, such as "7d-12345" and all points in that tile fall within that 7 day range. These tiles are written to DataStore, which is a key/value store. The key would be "7d-12345", and the value is essentially the string representation of the TimeSeries. The front end then requests these tiles via a dataserver.

**Comment by pjm17971** [comment]
**Calculating 30s base rates**

The SNMP batch Dataflow code takes a list of rows to `process_interface()`. Each row is a `[timestamp, value]` pair. The output of this function is a series of yielded dicts, each of which contains an aligned 30s base rate, along with the rest of the row to be inserted into BigQuery.

PyPond can do this calculation by converting the row list to points, creating a TimeSeries, and then using a simple Pipeline to do `align()` and then `rate()`. From each output Event we can yield the result as a dict. See the PyPond tests for how to do this.

**Comment by pjm17971** [comment]
** Calculating rollups **

The simplest place to use PyPond to do rollups would be to use its rollups functions. Instead of the grouping by 5m (or whatever window), you could assemble a Timeseries for the days worth of events (for a single interface). This would be taking the existing code and making a TimeSeries from the values. Then doing a flatmap where you can us ts.fixed_window_rollup("5m", {'value': Functions.avg}) to do the work. Then yield the result back one by one.

**Comment by pjm17971** [comment]
**Generating Tiles**

For generating tiles, you can use PyPond to do this, because the tile is just the serialization format for a TimeSeries. So build a ts from the points and then use `.to_string()` to make the tile. This way it will always be compatible with the client of the tiles (pond.js).

**Comment by montegoode** [comment]
This issue is way out of date and has been made irrelevant by more recent work.
